"""Initial migration

Revision ID: 30463abe4936
Revises: 
Create Date: 2025-02-15 12:08:28.231159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30463abe4936'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único da empresa'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome da empresa'),
    sa.Column('cnpj', sa.String(length=14), nullable=False, comment='CNPJ da empresa (14 dígitos, único)'),
    sa.Column('endereco', sa.String(length=200), nullable=True, comment='Endereço completo da empresa'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='E-mail de contato da empresa (único)'),
    sa.Column('telefone', sa.String(length=11), nullable=True, comment='Telefone de contato da empresa (10 ou 11 dígitos)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=False)
    op.create_table('obrigacoes_acessorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('periodicidade', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obrigacoes_acessorias_id'), 'obrigacoes_acessorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obrigacoes_acessorias_id'), table_name='obrigacoes_acessorias')
    op.drop_table('obrigacoes_acessorias')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
