"""Initial migration

Revision ID: 52c67468305f
Revises: 
Create Date: 2025-02-14 20:54:02.806528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c67468305f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único da empresa'),
    sa.Column('nome', sa.String(length=100), nullable=True, comment='Nome da empresa'),
    sa.Column('cnpj', sa.String(length=14), nullable=True, comment='CNPJ da empresa (14 dígitos, único)'),
    sa.Column('endereco', sa.String(length=200), nullable=True, comment='Endereço completo da empresa'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='E-mail de contato da empresa (único)'),
    sa.Column('telefone', sa.String(length=11), nullable=True, comment='Telefone de contato da empresa (10 ou 11 dígitos)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=False)
    op.create_table('obrigacoes_acessorias',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único da obrigação acessória'),
    sa.Column('nome', sa.String(length=100), nullable=True, comment='Nome da obrigação acessória'),
    sa.Column('periodicidade', sa.Enum('MENSAL', 'TRIMESTRAL', 'ANUAL', name='periodicidadeenum'), nullable=True, comment='Periodicidade da obrigação (mensal, trimestral, anual)'),
    sa.Column('empresa_id', sa.Integer(), nullable=True, comment='ID da empresa associada a esta obrigação'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obrigacoes_acessorias_id'), 'obrigacoes_acessorias', ['id'], unique=False)
    op.create_index(op.f('ix_obrigacoes_acessorias_nome'), 'obrigacoes_acessorias', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obrigacoes_acessorias_nome'), table_name='obrigacoes_acessorias')
    op.drop_index(op.f('ix_obrigacoes_acessorias_id'), table_name='obrigacoes_acessorias')
    op.drop_table('obrigacoes_acessorias')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
